image: maven:3.8.6

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/

stages:          # List of stages for jobs, and their order of execution
  - test
  - build
  - deploy

before_script:
  - chmod +x mvnw

.test-template: &test-template
  stage: tests
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /\[skip[ _-]Repository?\]/i
      - $SKIP_TESTS

test:
  <<: *test-template

build:
  stage: build
  script: ./mvnw package -DskipTests
  artifacts:
    paths:
      - target/supermarket-0.0.1-SNAPSHOT.jar

deploy:
  stage: deploy
  script:
    - echo "Deploy teste"
  only:
    - master
