image: maven:3.8.6

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/

stages:          # List of stages for jobs, and their order of execution
  - test
  - build
  - deploy

before_script:
  - chmod +x mvnw

test:
  stage: test
  script: ./mvnw test

build:
  stage: build
  script:
    - mvn clean compile verify
  artifacts:
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
        - target/failsafe-reports/TEST-*.xml

deploy:
  stage: deploy
  script:
    - echo "Deploy teste"
  only:
    - master
